services:
    dlabs.user.queue_handler.do_nothing:
        class: DLabs\UserBundle\Service\QueueHandler\DoNothingQueueHandler

#    dlabs.user.queue_handler.do_nothing__dummy:
#        class: stdClass
